FROM ubuntu:bionic as builder

MAINTAINER Brenden Blanco <bblanco@gmail.com>

RUN apt-get -qq update && \
    apt-get -y install pbuilder aptitude

COPY ./ /root/bcc

WORKDIR /root/bcc

RUN /usr/lib/pbuilder/pbuilder-satisfydepends && \
    ./scripts/build-deb.sh


FROM ubuntu:bionic

COPY --from=builder /root/bcc/*.deb /root/bcc/

RUN \
  apt-get update -y && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y python python3 binutils libelf1 kmod && \
  dpkg -i /root/bcc/*.deb
