#
# Copyright (C) 2016 Canonical
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
name: bcc
version: 0.7.0-20181122-2831-166fba57
summary: BPF Compiler Collection (BCC)
description: A toolkit for creating efficient kernel tracing and manipulation programs
confinement: strict
grade: stable
plugs:
    mount-observe: null
    system-observe: null
    system-trace: null
assumes: [snapd2.23]

parts:
    bcc:
        plugin: cmake
        configflags:
            - '-DCMAKE_INSTALL_PREFIX=/usr'
        source: ..
        source-type: git
        build-packages:
            - bison
            - build-essential
            - cmake
            - flex
            - libedit-dev
            - libllvm4.0
            - llvm-4.0-dev
            - libclang-4.0-dev
            - python
            - zlib1g-dev
            - libelf-dev
            - iperf
        stage-packages:
            - libc6
        prime:
            - usr/share/bcc/tools
            - usr/lib/*/lib*.so*
            - usr/lib/python2.7

            - -usr/share/bcc/tools/doc

    python-deps:
        plugin: python
        python-version: python2
        stage-packages:
            - libc6

apps:
    argdist:
        command: usr/share/bcc/tools/argdist
    bashreadline:
        command: usr/share/bcc/tools/bashreadline
    biolatency:
        command: usr/share/bcc/tools/biolatency
    biosnoop:
        command: usr/share/bcc/tools/biosnoop
    biotop:
        command: usr/share/bcc/tools/biotop
    bitesize:
        command: usr/share/bcc/tools/bitesize
    bpflist:
        command: usr/share/bcc/tools/bpflist
    btrfsdist:
        command: usr/share/bcc/tools/btrfsdist
    btrfsslower:
        command: usr/share/bcc/tools/btrfsslower
    cachestat:
        command: usr/share/bcc/tools/cachestat
    cachetop:
        command: usr/share/bcc/tools/cachetop
    capable:
        command: usr/share/bcc/tools/capable
    cobjnew:
        command: usr/share/bcc/tools/cobjnew
    cpudist:
        command: usr/share/bcc/tools/cpudist
    cpuunclaimed:
        command: usr/share/bcc/tools/cpuunclaimed
    dbslower:
        command: usr/share/bcc/tools/dbslower
    dbstat:
        command: usr/share/bcc/tools/dbstat
    dcsnoop:
        command: usr/share/bcc/tools/dcsnoop
    dcstat:
        command: usr/share/bcc/tools/dcstat
    deadlock-detector:
        command: usr/share/bcc/tools/deadlock_detector
    execsnoop:
        command: usr/share/bcc/tools/execsnoop
    ext4dist:
        command: usr/share/bcc/tools/ext4dist
    ext4slower:
        command: usr/share/bcc/tools/ext4slower
    filelife:
        command: usr/share/bcc/tools/filelife
    fileslower:
        command: usr/share/bcc/tools/fileslower
    filetop:
        command: usr/share/bcc/tools/filetop
    funccount:
        command: usr/share/bcc/tools/funccount
    funclatency:
        command: usr/share/bcc/tools/funclatency
    funcslower:
        command: usr/share/bcc/tools/funcslower
    gethostlatency:
        command: usr/share/bcc/tools/gethostlatency
    hardirqs:
        command: usr/share/bcc/tools/hardirqs
    javacalls:
        command: usr/share/bcc/tools/javacalls
    javaflow:
        command: usr/share/bcc/tools/javaflow
    javagc:
        command: usr/share/bcc/tools/javagc
    javaobjnew:
        command: usr/share/bcc/tools/javaobjnew
    javastat:
        command: usr/share/bcc/tools/javastat
    javathreads:
        command: usr/share/bcc/tools/javathreads
    killsnoop:
        command: usr/share/bcc/tools/killsnoop
    llcstat:
        command: usr/share/bcc/tools/llcstat
    mdflush:
        command: usr/share/bcc/tools/mdflush
    memleak:
        command: usr/share/bcc/tools/memleak
    mountsnoop:
        command: usr/share/bcc/tools/mountsnoop
    mysqld-qslower:
        command: usr/share/bcc/tools/mysqld_qslower
    nfsdist:
        command: usr/share/bcc/tools/nfsdist
    nfsslower:
        command: usr/share/bcc/tools/nfsslower
    nodegc:
        command: usr/share/bcc/tools/nodegc
    nodestat:
        command: usr/share/bcc/tools/nodestat
    offcputime:
        command: usr/share/bcc/tools/offcputime
    offwaketime:
        command: usr/share/bcc/tools/offwaketime
    oomkill:
        command: usr/share/bcc/tools/oomkill
    opensnoop:
        command: usr/share/bcc/tools/opensnoop
    perlcalls:
        command: usr/share/bcc/tools/perlcalls
    perlflow:
        command: usr/share/bcc/tools/perlflow
    perlstat:
        command: usr/share/bcc/tools/perlstat
    shmsnoop:
        command: usr/share/bcc/tools/shmsnoop
    sofdsnoop:
        command: usr/share/bcc/tools/sofdsnoop
    phpcalls:
        command: usr/share/bcc/tools/phpcalls
    phpflow:
        command: usr/share/bcc/tools/phpflow
    phpstat:
        command: usr/share/bcc/tools/phpstat
    pidpersec:
        command: usr/share/bcc/tools/pidpersec
    profile:
        command: usr/share/bcc/tools/profile
    pythoncalls:
        command: usr/share/bcc/tools/pythoncalls
    pythonflow:
        command: usr/share/bcc/tools/pythonflow
    pythongc:
        command: usr/share/bcc/tools/pythongc
    pythonstat:
        command: usr/share/bcc/tools/pythonstat
    rubycalls:
        command: usr/share/bcc/tools/rubycalls
    rubyflow:
        command: usr/share/bcc/tools/rubyflow
    rubygc:
        command: usr/share/bcc/tools/rubygc
    rubyobjnew:
        command: usr/share/bcc/tools/rubyobjnew
    rubystat:
        command: usr/share/bcc/tools/rubystat
    runqlat:
        command: usr/share/bcc/tools/runqlat
    runqlen:
        command: usr/share/bcc/tools/runqlen
    slabratetop:
        command: usr/share/bcc/tools/slabratetop
    softirqs:
        command: usr/share/bcc/tools/softirqs
    solisten:
        command: usr/share/bcc/tools/solisten
    sslsniff:
        command: usr/share/bcc/tools/sslsniff
    stackcount:
        command: usr/share/bcc/tools/stackcount
    statsnoop:
        command: usr/share/bcc/tools/statsnoop
    syncsnoop:
        command: usr/share/bcc/tools/syncsnoop
    syscount:
        command: usr/share/bcc/tools/syscount
    tcpaccept:
        command: usr/share/bcc/tools/tcpaccept
    tcpconnect:
        command: usr/share/bcc/tools/tcpconnect
    tcpconnlat:
        command: usr/share/bcc/tools/tcpconnlat
    tcplife:
        command: usr/share/bcc/tools/tcplife
    tcpretrans:
        command: usr/share/bcc/tools/tcpretrans
    tcptop:
        command: usr/share/bcc/tools/tcptop
    tcptracer:
        command: usr/share/bcc/tools/tcptracer
    tplist:
        command: usr/share/bcc/tools/tplist
    trace:
        command: usr/share/bcc/tools/trace
    ttysnoop:
        command: usr/share/bcc/tools/ttysnoop
    ucalls:
        command: usr/share/bcc/tools/lib/ucalls
    uflow:
        command: usr/share/bcc/tools/lib/uflow
    ugc:
        command: usr/share/bcc/tools/lib/ugc
    uobjnew:
        command: usr/share/bcc/tools/lib/uobjnew
    ustat:
        command: usr/share/bcc/tools/lib/ustat
    uthreads:
        command: usr/share/bcc/tools/lib/uthreads
    vfscount:
        command: usr/share/bcc/tools/vfscount
    vfsstat:
        command: usr/share/bcc/tools/vfsstat
    wakeuptime:
        command: usr/share/bcc/tools/wakeuptime
    xfsdist:
        command: usr/share/bcc/tools/xfsdist
    xfsslower:
        command: usr/share/bcc/tools/xfsslower
    zfsdist:
        command: usr/share/bcc/tools/zfsdist
    zfsslower:
        command: usr/share/bcc/tools/zfsslower

# vim: set ai et sts=4 tabstop=4 sw=4:
