.TH netqtop 8 "2020-07-30" "USER COMMANDS"
.SH NAME
netqtop \- Summarize PPS, BPS, average size of packets and packet counts ordered by packet sizes 
on each queue of a network interface.
.SH SYNOPSIS
.B netqtop [\-n nic] [\-i interval] 
.SH DESCRIPTION
netqtop accounts statistics of both transmitted and received packets on each queue of 
a specified network interface to help developers check if its traffic load is balanced. 
The result is displayed as a table with columns of PPS, BPS, average size and 
packet counts in range [0,64), [64, 5120), [512, 2048), [2048, 16K), [16K, 64K). 
This is printed every given interval in seconds.

This tool uses the net:net_dev_start_xmit and net:netif_receive_skb kernel tracepoints. 
Since this uses BPF, only the root user can use this tool.

.SH REQUIREMENTS
CONFIG_bpf and bcc
.SH OPTIONS
.TP
\-n NIC
Specify the network interface card
.TP
\-i INTERVAL
Print results every INTERVAL seconds.
The default value is 1.
.SH EXAMPLES
.TP
Account statistics of eth0 and output every 2 seconds:
#
.B netqtop -n eth0 -i 2
.SH OVERHEAD
netqtop introduces a maximum overhead of 20% sockperf PPS drop while 
the tool(with printing interval set to 1 second) and sockperf 
run on the same core. In multi-thread cases, the overhead could be 
less significant. 

It also increases ping-pong latency by 10%, which is about 0.4 usec. 
.SH SOURCE
This is from bcc
.IP
https://github.com/iovisor/bcc
.PP
Also look in the bcc distribution for a netqtop_example.txt file containing
example usage, output and commentary for this tool.
.SH OS 
Linux
.SH STABILITY
Unstable - in development
.SH AUTHOR
Fu Yuan